### ISSUE TITLE
是否能取代 marked 作为 hexo 中的渲染引擎

### ISSUE THREAD

**Issue by XhinLiang** [shd101wyy/mume#107]

**Comment by XhinLiang** [comment]
试了下，能实现功能，但是渲染格式跟主题不匹配了，无奈放弃。。
其实应该是能做到的，只是麻烦点儿...

**Comment by yangsenius** [comment]
@XhinLiang 请问兄弟怎么做到的？是把hexo自带的css文件，链接成这个的吗？具体操作怎么弄
