### ISSUE TITLE
Update Vega Lite

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/mume#120]
Adds data generators in version 3.2.0.

Sequence Generator is the powerful data source like:

```
"data": {"sequence": {"start": 0, "stop": 1001, "step": 1, "as": "posX"}}
```

https://vega.github.io/vega-lite/docs/data.html#sequence

Please update Vega Lite to new version.

**Comment by shd101wyy** [comment]
Hi @kachkaev could you please take a look at this issue? I don't know how to upgrade `Vega-Lite`. Thank you!

**Comment by tmori3y2** [comment]
According to https://github.com/shd101wyy/mume/blob/master/dependencies/README.md, mume depends on vega-lite version 3.0.0-rc14.

Some new features fail with MPE.

ex) https://vega.github.io/vega-lite/docs/data.html#sequence

```vega-lite
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "description": "Plots a function using a generated sequence.",
  "width": 300,
  "height": 150,
  "data": {"sequence": {"start": 0, "stop": 12.7, "step": 0.1, "as": "u"}},
  "transform": [
    {"calculate": "sin(datum.u)", "as": "v"},
    {"calculate": "cos(datum.u)", "as": "w"}
  ],
  "layer": [
    {
      "mark": "line",
      "encoding": {
        "x": {"field": "u", "type": "quantitative", "title": "x"},
        "y": {"field": "v", "type": "quantitative", "title": "sin(x)"}
      }
    },
    {
      "mark": {"type": "line", "stroke": "firebrick"},
      "encoding": {
        "x": {"field": "u", "type": "quantitative"},
        "y": {"field": "w", "type": "quantitative", "title": "cos(x)"}
      }
    }
  ]
}
```

The result is ...

 TypeError: Cannot read property 'url' of undefined

**Comment by shd101wyy** [comment]
Can you try to manually download the latest vega-lite and replace the file located at `.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.4.0/node_modules/@shd101wyy/mume/dependencies/vega-lite/vega-lite.min.js` to see if it works? Thank you!

**Comment by kachkaev** [comment]
@shd101wyy I'm in a process of submitting a PR that would update all vega libraries. Currently buzy doing work work, but will be happy to finish it in a few days if this can wait.

**Comment by shd101wyy** [comment]
@kachkaev  No hurry. Please take your time. I have been busy too 😂 haha.

**Comment by tmori3y2** [comment]
> Can you try to manually download the latest vega-lite and replace the file located at `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.4.0/node_modules/@shd101wyy/mume/dependencies/vega-lite/vega-lite.min.js` to see if it works? Thank you!

I was tried to update by manually, and made pdf by puppeteer.

[vega-lite-v3.3.0.pdf](https://github.com/shd101wyy/mume/files/3232436/vega-lite-v3.3.0.pdf)
