### ISSUE TITLE
Inconsistent body padding at 914px threshold (Quick fix)

### ISSUE THREAD

**Issue by andrewdelong** [shd101wyy/mume#121]
The padding currently flips from 2em to 0em as the page width crosses 914px, resulting in a visual jump while resizing.

The change below to `styles/src/style-template.less` seems to fix it. (I only tested in Chrome.)
![image](https://user-images.githubusercontent.com/48439/58346345-a72c4a00-7e28-11e9-929f-3def1f9e739c.png)

Thanks for the superb extension!

**Comment by shd101wyy** [comment]
I will include your change in version `0.3.9`. Please see the reference above. Thanks!

Closing this issue now :)
