### ISSUE TITLE
KaTeX macro configuration

### ISSUE THREAD

**Issue by andrewdelong** [shd101wyy/mume#129]
KaTeX macros don't seem to be configurable, nor pulled from the MathJax config.

I can imagine two solutions:
1. Add `~/.mume/katex_config.js` and make it discoverable via `Open KaTeX Config` command, or
2. Pull the KaTeX macros directly from the `TeX` field of `mathjax_config.js` so that users can switch between KaTeX and MathJax without needing to keep the two macro configs in sync.

The most flexible thing might be to do (2) by default, i.e. when there's no KaTeX config, but still support (1) for users who want to customize KaTeX independently.

**Workaround:** For now I'm editing the `macros` variable in my local `parse-math.js` file.
```javascript
const macros = {
    "\\ba":     "\\bm{a}",
    "\\balpha": "\\bm{\\alpha}",
    ...
}
```
which for me is located at `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.4.0/node_modules/@shd101wyy/mume/out/src/parse-math.js`. I keep a backup in case vscode clobbers my file in an update.

**Comment by shd101wyy** [comment]
Sure will do in next version. Thank you for your suggestion!

**Comment by shd101wyy** [comment]
Supported now in `0.4.6`. Thank you.
