### ISSUE TITLE
Puppeteer Options

### ISSUE THREAD

**Issue by AlexejLiebenthal** [shd101wyy/mume#149]
Please provide an overload for puppeteer options, so that we can start it in `--no-sandbox` mode to allow CI PDF generation with this package. (E.g. Docker, Gitlab-CI etc.)
The problem is that we can't control the mode from outside with an global variable of puppeteer as I know. So this package should allow somehow access to this dependency.

As I can see the change should be made in [this method](https://github.com/shd101wyy/mume/blob/f6b7fcc66938dd2fbd1669c4c9ff498d77b187f0/src/markdown-engine.ts#L1693)

And then call `await puppeteer.launch()` with this options.

Another possible solution could be only to have an additional boolean flag for `--no-sandbox`

**Comment by shd101wyy** [comment]
It's probably already too late, but I just added one option `puppeteerArgs`. Please check the README.md. Thanks
