### ISSUE TITLE
mermaid graph in "Markdown Preview Enhanced" not display properly

### ISSUE THREAD

**Issue by qxo** [shd101wyy/mume#167]
mermaid graph显示不太正常这个问题是这应该在这个项目解决不？
两个问题： 1. 底色不对 2. 边线没显示
![image](https://raw.githubusercontent.com/qxo/images/master/mermaid-graph-display-issue.png)

重现问题样例如下：
```mermaid
graph LR;
　　用户 -->|更新|发布机;

```

**Comment by shd101wyy** [comment]
这个需要你去插件设置里面更改下 `mermaidTheme` 然后再改回来就好了

**Comment by qxo** [comment]
> 这个需要你去插件设置里面更改下 `mermaidTheme` 然后再改回来就好了

还真是，原来还有这个坑：修改markdown-preview-enhanced.mermaidTheme设置就可以了
多谢：）

看来有问题要多问啊：）

**Comment by shd101wyy** [comment]
其实这个 bug 我也不知道是咋回事儿哈哈，莫名其妙地有时候会出现
