### ISSUE TITLE
Setting for mathjax config file path

### ISSUE THREAD

**Issue by gabyx** [shd101wyy/mume#169]
Can we add a setting defaulting to `~/mume/mathjax_config.js` for the mathjax config.
I would like to be able to use a mathjax config somewhere else local to the working directory.

Is a PR welcome?

**Comment by shd101wyy** [comment]
Yeah PR is welcome

**Comment by gabyx** [comment]
See #173 . Thanks for merging and reviewing. Maybe you can make the necessary changes directly if any needed.
