### ISSUE TITLE
Support markdown-it-admonition

### ISSUE THREAD

**Issue by matrix-ranger** [shd101wyy/mume#225]
I enjoy this extension very much. Can we further support [Admonition](https://www.npmjs.com/package/markdown-it-admonition) syntax in markdown? Like what [Markdown Extended](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended#admonition) and [MkDocs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) does.

**Comment by shd101wyy** [comment]
Will be supported in this PR ^^^
