### ISSUE TITLE
Allow for shortcuts in code chunk options

### ISSUE THREAD

**Issue by kachkaev** [shd101wyy/mume#29]
I'd like to propose an improvement to command chunk options and am curious what you think. Let's take this example:

````markdown
```python {cmd=true hide=true}
````

It seems intuitive to omit `=true` and simply write:
````markdown
```python {cmd hide}
````
However, the current implementation treats the above options as: `{cmd: hide}` because a space is the same as `=` for the [interpreter](https://github.com/shd101wyy/mume/blob/b73cc2f8d9f4bb0b0bb4515411bd8e8eabae3772/src/utility.ts#L456). This is less obvious, especially in cases like these ones:

````markdown
```python {cmd .class1 .class2 hide}
````
↓
`{ class: 'class1 class2', cmd: 'hide' }`

````markdown
```python {cmd}
````
↓
`{}`

````markdown
```python {cmd output="path.html" hide}
````
↓
`{ cmd: 'output', 'path.html': 'hide' }`

How about making `=` necessary for `key=value` options and when it is omitted, how about treating the input as `key=true`?

This improvement opens up a new range of opportunities for shortcuts, which can be very concise  and thus time-saving for advanced users. For example, `{h}` can unwrap to `{cmd=true hide=true}` in the background. I'm not proposing this next step at the moment, just sharing thoughts on future benefits I see.

I can submit a PR for assuming` =true` by default. WDYT?

**Comment by kachkaev** [comment]
ping @shd101wyy 😃

**Comment by shd101wyy** [comment]
Hi @kachkaev ,

Yes that's a very good idea. I will be busy recently, so it would be great if you could submit a pull request.
The function that you might need to have a look is called [parseAttributes in utility.ts](https://github.com/shd101wyy/mume/blob/master/src/utility.ts#L460).

Thank you very much

**Comment by kachkaev** [comment]
OK, will work on a PR tomorrow!
