### ISSUE TITLE
关于Node JS环境下安装的问题

### ISSUE THREAD

**Issue by Holy-Shine** [shd101wyy/mume#35]
冒昧得问下作者大大，这个渲染器可以用Node.js的包管理器下载安装吗

**Comment by shd101wyy** [comment]
可以
https://github.com/shd101wyy/mume

**Comment by Holy-Shine** [comment]
那可以用ruby gem吗

**Comment by shd101wyy** [comment]
@Holy-Shine 不可以，这个是 nodejs 的项目。
