### ISSUE TITLE
Inconsistent code chunk behaviour for ```math

### ISSUE THREAD

**Issue by kachkaev** [shd101wyy/mume#36]
[According to the docs](https://shd101wyy.github.io/markdown-preview-enhanced/#/math), math blocks can be currently rendered using `$$...$$`, `\[...\]` or ```` ```math ````. However, the latter option creates a counter-intuitive special case, which may be undesired by mume users.

When there is an intention to make a code block live, users are usually offered to add `{cmd=true}` to the block (or just `{cmd}` after https://github.com/shd101wyy/mume/pull/31). Besides, they are likely to know that `{hide=true}` (or just `{hide}`) would remove the math source and only keep the rendered result. Thus, a ’standard’ intended use of ```` ```math ```` for a newcomer would be the following:

````md
source only:
```math
x=42
```

source followed by the rendered formula:
```math {cmd}
x=42
```

rendered formula only:
```math {cmd hide}
x=42
```
````

Unfortunately, the above would not work, because ```` ```math ```` is currently treated in a [special way](https://github.com/shd101wyy/mume/blob/f6f56fa3bfca7d0c51236ef67ac863f147f7054a/src/markdown-engine.ts#L482-L489). The existing implementation, however, does not support extra options such as ```` ```math {.class}````. Even typing ```` ```math {} ```` breaks the magic, because the special condition does not accept anything after the language keyword.

IMO it'd be beneficial to disable this special case for ```` ```math ```` and advise existing users to switch to either `$$` or ```` ```math {cmd hide} ```` in order to maintain consistency. The good thing is that the second notation will be able to support things like `.custom-class` and other perks that are common for any all code chunks. Importantly, users will be finally able to show the source code for the formula together with the rendered result, which is currently impossible and requires duplicating the math block in the markdown source (it is either printed or executed, but never both):

````md
```
very long formula
```

```math
very long formula
```
````
instead of just

````md
```math {cmd}
very long formula
```
````

I can fix this issue by pushing a new commit to https://github.com/shd101wyy/mume/pull/34 if you agree with my arguments for this change. WDYT @shd101wyy?

**Comment by shd101wyy** [comment]
I haven't thought much about it. 
Maybe leave it unchanged for now in pull request #34.
We can change it in another pull request in the future.
Thank you.

**Comment by kachkaev** [comment]
Thanks for adding me as a collaborator @shd101wyy! I'll be happy to help you with reviewing and merging PRs from others, but I'd prefer to also be reviewed when it comes to own PRs (just to always have a second pair of eyes and not end up with silly mistakes in master).

I understand that you won't be able to look though all of my stuff in the near future, but if you see something you can give the green light to, I'll be happy to merge those things and prepare a new release.

**Comment by shd101wyy** [comment]
Yeah that would be nice.

**Comment by kachkaev** [comment]
Good. I pushed a new [commit](https://github.com/shd101wyy/mume/pull/34/commits/c2cfa6b11475a4d6885c867496532d35f318bee5) to https://github.com/shd101wyy/mume/pull/34 where treating ```` ```math ``` was made similar to `vega` and `vega-lite`. Additional attributes like `{cmd=false}` as still ignored because there is no handling of this for all diagrams, however, at least these attributes do not break the behaviour.

I'll be happy to work on a slightly more coherent way of handling attributes in diagrams and code blocks once we finish off with the existing PRs (too much changes are chaining otherwise) :–)
