### ISSUE TITLE
config to not generate toc in html output

### ISSUE THREAD

**Issue by mzhng** [shd101wyy/mume#80]
I couldn't find any reference in the README about how to generate html (`engine.htmlExport`) without the table of content. Is it possible? I guess there is some option I haven't found yet, because markdown-enhanced doesn't generate the toc by default.

**Comment by leozzyzheng** [comment]
set enableScriptExecution to false

**Comment by shd101wyy** [comment]
Oops sorry I just saw your question. @leozzyzheng is right. You can also configure it in your front-matter:

https://shd101wyy.github.io/markdown-preview-enhanced/#/html?id=configuration

Thanks
