### ISSUE TITLE
markdownExport fails to run ImageMagicks convert on windows

### ISSUE THREAD

**Issue by s0ren** [shd101wyy/mume#96]
On windows 10 I keep getting:

```
Error: ImageMagick is required to be installed to convert svg to png.
Error: Command failed: convert C:\Users\smag\AppData\Local\Temp\mume-svg118102-12668-1lvlnjv.rk2q.svg C:\Users\[userid]\Desktop\MPE_tryout\assets\1d71d338ce53e8b5769d5adbe4ce262b0.png
Invalid Parameter - C:\Users\[userid]\Desktop\MPE_tryout\assets\1d71d338ce53e8b5769d5adbe4ce262b0.png
```
The first line is printed from line 16 of `src/magick.ts`, but the third line is actually from a build in windows command shadowing for ImageMagicks `convert`. 
See http://www.imagemagick.org/Usage/windows/#convert_issue.

They suggest that applications using these tools rename ImageMagicks tools, and configure where to find them.

So I guess that ImageMagick tools shold have a imagemagick.json in ~/.mume/

this is a duplicate of https://github.com/shd101wyy/markdown-preview-enhanced/issues/1008#issue-376779674, but I suppose its more relevant here...

I hope there will be a fix some how.

**Comment by shd101wyy** [comment]
I see. So for windows we probably still want to use `magick` command.

**Comment by Mrazator** [comment]
How are you running this on linux? Please have a look at my proposed solution - using imagemagick-cli as an npm package.
